### ISSUE TITLE
Running gitviz on ubuntu-based system fails

### ISSUE THREAD

**Issue by sparsick** [chr1shaefn3r/gitviz#1]
I install gitviz with the command `sudo npm install --global gitviz`

Used NPM version is 5.5.1.

When I run the command `gitviz --help`, following error message is thrown:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/gitviz/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

It seems that there are problems with the package `nodegit`. I tried to install `nodegit` directly, but unfortunately it fails with the error message:

```
> nodegit@0.20.3 install /usr/lib/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/nodegit/vendor/openssl/openssl' }
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.20.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.20.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sparsick/.npm/_logs/2017-11-09T11_09_04_098Z-debug.log

```

Maybe, it matches a problem in nodegit that is described in  https://github.com/nodegit/nodegit/issues/1385

My OS is:
```
Distributor ID: LinuxMint
Description:    Linux Mint 18.2 Sonya
Release:        18.2
Codename:       sonya
based on: Ubuntu 16.04 LTE
```

**Comment by chr1shaefn3r** [comment]
Well, yeah, nodegit is a pain in the a*** dependency.

I just tried to install gitviz on Ubuntu 17.10 with node 8.9.1 and npm 5.5.1, received the same error as you did. And I also face issues installing nodegit directly, although my error message looks quite different. Mine is complaining about "error: No crypto library found". (Will try with libssl-dev again)
Your error message, more specific:
`/usr/lib/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied`
looks like you tried to install nodegit globally and forgot "sudo"? Maybe?

All in all: Really need to get rid of the binary dependencies :/

Cheers,
Christoph

**Comment by sparsick** [comment]
I ran every install command with `sudo` . Therefore, I don't understand this permission issue. By the way, in https://github.com/nodegit/nodegit/issues/1385 , they have the same permission issues.

**Comment by chr1shaefn3r** [comment]
Ok, that rules that out. By the way, I saw their permission issue, but they didn't state whether they used sudo either.

I fear I can't help you right now.
Because nodegit was tricky to get right in the past, I thought about a Dockerfile which would have, e.g. a "/in" and a "/out" volume. And then gitviz could be used like so:
"docker run gitviz -v /tmp/git-repo:/in -v /tmp/visualization:/out"
But I didn't get around to set this up, would happily review and test a pull request, though.

**Comment by sparsick** [comment]
I'll try to build a Dockerfile for it. But I promise nothing. :)

Thank you for your help and time.

**Comment by aguidrevitch** [comment]
For Docker, there is a fix to build nodegit

```
npm -g config set user root
```

Or, as one-time workaround, use --unsafe-perm
```
docker run --rm -it node:carbon npm -g install nodegit --unsafe-perm
```

**Comment by sparsick** [comment]
@aguidrevitch thank you for your hint. It helped me to install `nodegit` on my machine (not in a docker container).  But unfortunately, I get the same error that is described in the initial describtion.
